### ISSUE TITLE
执行wordFreqKafkaMysql报这个错

### ISSUE THREAD

**Issue by neatlife** [xlturing/spark-streaming-action#2]
![image](https://user-images.githubusercontent.com/4076198/60591739-abf1ff80-9dd1-11e9-82af-a2aa82bab7e4.png)

**Comment by xlturing** [comment]
感觉是Kafka没数据吧？

**Comment by xlturing** [comment]
感觉是Kafka没数据吧？

**Comment by neatlife** [comment]
![image](https://user-images.githubusercontent.com/4076198/60641621-29b01c80-9e5f-11e9-925b-dde5d87fd012.png)

一开始我也以为没数据，但是到topic ui里确认了是有数据的

**Comment by neatlife** [comment]
已解决，kafka监听的ip和spark链接的kafka ip不一致导致的
