### ISSUE TITLE
[图书勘误]

### ISSUE THREAD

**Issue by mapxn** [xlturing/spark-streaming-action#3]
p65：4.3.2 已经支持Fllume1.6.0 --》 Fllume --> Flume
p82: 倒数第三段 其中一个回作为主分支--》回--> 会
p86: 5.2.4 我们可以利用Kfka-consumer-groups.sh --》Kfka-->Kafka

**Comment by xlturing** [comment]
多谢~

**Comment by xlturing** [comment]
https://mp.weixin.qq.com/s?__biz=MzAxNzMzOTk5MQ==&tempkey=MTAzMF9jMlBsMXh4Mi9VeHFiZFdDUFZuelM2RzJHUU9rV0lCTFprV1dzRzZ6Q0thYmJvTDVKVm9GT1Ywdm5kblBXSmxGaHVoTnRXaUttWnk3ZVg4SHlTaUctMGg0MEZ0NG1NeG4xbnIxdXYtY2JKcVdiRzBjdEpnYVdYalVCaHBoYzhwbGRzU2ExT1g1U01ZQUpSMmpTdURxTE5RTFMwd3Jobm1Cb0ExQjVBfn4%3D&chksm=0c07c9053b7040135f0f3360a3716bf518ec04805145696f67b00fa7f3d205022d3a904db773#rd
已更新在公众号勘误~

**Comment by mapxn** [comment]
p103 (1)构建一个流式上线文--》 线-->下
p113 倒数第四行：所以如果设置过段的批处理时间--》 段-->短

**Comment by xlturing** [comment]
收到~
