### ISSUE TITLE
源码第八章KafkaCluster.scala报错

### ISSUE THREAD

**Issue by mapxn** [xlturing/spark-streaming-action#4]
感谢作者的精心撰写，在实战项目当中，我使用IDEA开发环境，在导入第八章词频统计处理的代码后，在`KafkaCluster.scala`出现一个奇怪的错误，如下图：
猜测是scala版本不符合？？谷歌没有找到类似的错误
![image](https://user-images.githubusercontent.com/16299874/66714156-cd598300-ede5-11e9-82f8-44b4da0cb393.png)
idea的scala插件版本是2.11.8

`Random.shuffle(config.seedBrokers)`方法得到的貌似是一个`mutable.ArrayOps[(String,Int)]`的类型

**Comment by immapan** [comment]
如果不shuffle的话，是不会报错的。请问在这里shuffle的目的是什么？

**Comment by mapxn** [comment]
ok我了解了，KafkaCluster.scala是引入的spark源码，kafka-0-10版本及以后就弃用了。
而当前项目并没有引用到报错的`getPartitionMetadata`方法
我的解决方案是:
删除`Random.Shuffle()`方法，直接传参数。
整个项目并没有用到这个方法，只需要这块不报错，理论上整个项目就可以正常运行！
